controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["left_front_wheel_joint", "left_rear_wheel_joint"]
      right_wheel_names: ["right_front_wheel_joint", "right_rear_wheel_joint"]
      wheel_separation: 0.30   # approximate between wheel centers left-right
      wheel_radius: 0.05
      publish_rate: 50
      cmd_vel_timeout: 0.5
      use_stamped_vel: false
      base_frame_id: base_link
      pose_covariance_diagonal: [0.001, 0.001, 1000.0, 1000.0, 1000.0, 0.001]
      twist_covariance_diagonal: [0.001, 0.001, 1000.0, 1000.0, 1000.0, 0.001]

    # Optional: control limits
      linear.x.has_velocity_limits: true
      linear.x.max_velocity: 1.0
      linear.x.min_velocity: -1.0
      angular.z.has_velocity_limits: true
      angular.z.max_velocity: 2.0
      angular.z.min_velocity: -2.0
